### ISSUE TITLE
Streamline UI toast usage

### ISSUE THREAD

**Issue by ropali** [ropali/dockyard#10]
Some of the places react-toast is used for showing toast messages and in settings page SweetAleart is used as toast message. Use only one of the way to show toast message. SweetAlert is mostly prefered but open to other suggestions.

**Comment by morph1nX** [comment]
[React Toastify](https://fkhadra.github.io/react-toastify/introduction/) can be a good option if information alerts are the only use case

**Comment by ropali** [comment]
> [React Toastify](https://fkhadra.github.io/react-toastify/introduction/) can be a good option if information alerts are the only use case

Yes but SweetAlert provides a way to use it as a modal for capturing inputs from users and I have cases where I want a confirmation from the user before performing operation.
