### ISSUE TITLE
Can't change terminal on MacOS

### ISSUE THREAD

**Issue by elcharitas** [ropali/dockyard#12]
![Screenshot 2024-09-21 at 08 55 56](https://github.com/user-attachments/assets/527e1eda-afd3-48d8-8821-e8190b2bdfff)

I would like to change the default terminal to iterm2 but that isn't woprking

**Comment by ropali** [comment]
@elcharitas I don't have a Mac machine so It is difficult for me to debug this till I get the hold of a mac or setup a VM. If possible you can submit a PR otherwise please wait for sometime to get this fixed.

**Comment by ropali** [comment]
@elcharitas it has been fixed and will be released soon
