### ISSUE TITLE
Publish to AUR

### ISSUE THREAD

**Issue by dougg0k** [ropali/dockyard#16]
https://wiki.archlinux.org/title/Arch_User_Repository

https://ashishkus.hashnode.dev/aur-and-publish-your-first-package-guide

https://github.com/marketplace/actions/publish-aur-package

**Comment by ropali** [comment]
@dougg0k Thanks for the suggestion! I have already have this in my backlog to publish dockyard through different channels. If you are interested then you can take this up.
