### ISSUE TITLE
[BUG] 0.4.0 only shows white screen on M4 Max

### ISSUE THREAD

**Issue by BornSupercharged** [ropali/dockyard#31]
**Describe the bug**
The app doesn't display anything anymore. Downgrading back to 0.3.0, it works fine again. 

In 0.4.0, the Dockyard window is just white. If I go to the menu bar and click "About dockyard", that window properly displays. But the main window is simply white.
![image](https://github.com/user-attachments/assets/084705bf-f21b-45a1-9335-6870b0db5555)

**To Reproduce**
White screen when running Dockyard 0.4.0. 
[dockyard_0.4.0_aarch64.dmg](https://github.com/ropali/dockyard/releases/download/v0.4.0/dockyard_0.4.0_aarch64.dmg)

Upgrade to Dockyard 0.4.0 from any older Dockyard, i.e. dockyard_0.3.0_aarch64.dmg

**Expected behavior**
App should work properly

**Desktop:**
- Hardware: MacBook Pro M4 Max 
 - OS: macOS Sequoia 15.1
 - Docker version: 27.3.1, build ce12230

**Comment by BornSupercharged** [comment]
When building from source, 0.4.0 runs properly.

**Comment by ropali** [comment]
It looks like its not specific to M1 mac. I am also getting the same issue if I install .deb package from release. Let me investigate it. Thanks for reporting @BornSupercharged

**Comment by ropali** [comment]
@BornSupercharged I figured out the issue. It was due improperly configured build command. The build command was for JS code and migrated to ts and build command was not updated properly. Apart from the in the tsconfig it was also no reading the .jsx file while compiling the js code. 

This seems to fix the white screen issue but for some odd reason the release pipelines are failing. Can you test this on your local by building this project from source? that will be a great help. Thanks!

**Comment by BornSupercharged** [comment]
@ropali yes, ```npm run tauri build``` now results in a dockyard.app file that installs and runs properly, no more white screen.

**Comment by BornSupercharged** [comment]
[dockyard_0.4.1_aarch64.dmg.zip](https://github.com/user-attachments/files/18241504/dockyard_0.4.1_aarch64.dmg.zip)
I've uploaded the resulting DMG for aarch64 here as well.

**Comment by BornSupercharged** [comment]
@ropali release 0.4.1 works fine yes.
